### ISSUE TITLE
Support updating a chain to different version

### ISSUE THREAD

**Issue by netoneko** [orbs-network/nebula#19]
Scenario with 3 chains (42, 92, 73):

```
update(42, "feature/one-chain")
update(92, "some-other-chain")
```

result: `{42: "feature/one-chain", 92: "some-other-chain", 73: "master"}`

Should probably be done through intermediate storage of the state in cache folder.

**Comment by itamararjuan** [comment]
@netoneko can I close this?

**Comment by netoneko** [comment]
Yes.
